# Generated by Django 4.0 on 2022-10-04 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comun', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipotelefono',
            options={'verbose_name': 'Tipo Telefono', 'verbose_name_plural': 'Telefonos'},
        ),
    ]
