# Generated by Django 4.1.1 on 2022-09-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35, unique=True, verbose_name='nombre')),
                ('descripcion', models.TextField(max_length=255, verbose_name='descripcion')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='precio')),
                ('stock', models.PositiveIntegerField(verbose_name='stock')),
                ('fecha_ingreso', models.DateField(verbose_name='fecha de ingreso')),
                ('estado', models.BooleanField(default=True, verbose_name='disponible')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
            },
        ),
    ]
