# Generated by Django 4.1.1 on 2022-09-27 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_categoria_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'Marca',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='talla',
            field=models.CharField(default='', max_length=35, unique=True, verbose_name='talla'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='nombre'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.marca'),
            preserve_default=False,
        ),
    ]
