# Generated by Django 4.1.1 on 2022-09-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_marca_producto_talla_alter_producto_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=35, unique=True, verbose_name='nombre'),
        ),
    ]
