# Generated by Django 4.1.1 on 2022-09-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_producto_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='nombre',
        ),
        migrations.AddField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(default='', max_length=35, unique=True, verbose_name='nombre_cat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marca',
            name='marca',
            field=models.CharField(default='', max_length=35, unique=True, verbose_name='marca'),
            preserve_default=False,
        ),
    ]
