# Generated by Django 4.1.1 on 2022-09-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_categoria_nombre_remove_marca_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(max_length=35, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='marca',
            field=models.CharField(max_length=35, unique=True, verbose_name='nombre'),
        ),
    ]
