# Generated by Django 4.0 on 2022-10-06 17:51

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_venta_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(max_length=35, unique=True, verbose_name='nombreTalla')),
            ],
            options={
                'verbose_name': 'Talla',
                'verbose_name_plural': 'Tallas',
                'db_table': 'Talla',
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='nombre_cliente',
            field=models.CharField(default='', max_length=40, verbose_name='talla'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=models.CharField(max_length=35, verbose_name=store.models.Talla),
        ),
    ]
