# Generated by Django 4.0 on 2022-10-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_talla_venta_nombre_cliente_alter_producto_talla'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='img',
            field=models.ImageField(default='', upload_to='img', verbose_name='marca'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='talla',
            name='talla',
            field=models.CharField(max_length=35, unique=True, verbose_name='Talla'),
        ),
    ]
