# Generated by Django 4.0 on 2022-10-06 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_marca_img_alter_talla_talla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='img',
        ),
    ]
