# Generated by Django 4.0 on 2022-11-03 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_producto_talla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.talla'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='nombre_cliente',
            field=models.CharField(max_length=40, verbose_name='nombre cliente'),
        ),
    ]
