# Generated by Django 4.0 on 2022-11-03 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_producto_nombre_alter_producto_talla_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.talla'),
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('nombre', 'talla')},
        ),
    ]
