# Generated by Django 4.0.4 on 2022-05-19 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellido')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, verbose_name='genero')),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha nacimiento')),
                ('estado', models.BooleanField(default=True)),
                ('dpi', models.CharField(max_length=14, unique=True, verbose_name='DPI')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'unique_together': {('nombre', 'apellido')},
            },
        ),
        migrations.CreateModel(
            name='TelefonoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=12, verbose_name='telefono')),
                ('Empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TelEmpleado', to='comun.tipotelefono', verbose_name='Tipo Telefono')),
            ],
            options={
                'verbose_name': 'Telefono',
                'verbose_name_plural': 'Telefonos',
                'db_table': 'telefono_empleado',
            },
        ),
    ]
